package com.ecom.service;

import java.security.SecureRandom;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;

@Service
public class OtpService {
	
	@Autowired
    private JavaMailSender mailSender;
	
	public String sendOtp(String email) {
	    // Generate OTP
	    String otp = genereateOtp();

	    // HTML content with inlined Tailwind CSS
	    String emailContent = 
	        "<!DOCTYPE html>" +
	        "<html lang='en'>" +
	        "<head>" +
	        "<meta charset='UTF-8'>" +
	        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>" +
	        "<title>OTP for Password Reset</title>" +
	        "<style>" +
	        "/* Inlined styles generated by the Tailwind CSS Email tool */" +
	        ".container { max-width: 600px; margin: 0 auto; padding: 20px; background-color: #ffffff; border-radius: 8px; }" +
	        ".header { text-align: center; font-size: 24px; font-weight: bold; color: #1D4ED8; margin-bottom: 20px; }" +
	        ".otp { font-size: 32px; font-weight: bold; color: #4CAF50; padding: 12px 24px; background-color: #E2E8F0; border-radius: 8px; margin-bottom: 20px; }" +
	        ".footer { text-align: center; font-size: 14px; color: #6B7280; margin-top: 20px; }" +
	        ".button { background-color: #4CAF50; color: white; padding: 12px 25px; border-radius: 8px; text-decoration: none; font-weight: bold; }" +
	        "</style>" +
	        "</head>" +
	        "<body>" +
	        "<div class='container'>" +
	        "<div class='header'>OTP for Password Reset</div>" +
	        "<p>Hello,</p>" +
	        "<p>Your OTP for resetting your password is:</p>" +
	        "<div class='otp'>" + otp + "</div>" +
	        "<p>If you did not request this, please ignore this email.</p>" +
	        "<a href='https://example.com/reset-password' class='button'>Reset Password</a>" +
	        "<div class='footer'>&copy; 2024 E-com Spring. All Rights Reserved.</div>" +
	        "</div>" +
	        "</body>" +
	        "</html>";

	    try {
	        MimeMessage message = mailSender.createMimeMessage();
	        MimeMessageHelper helper = new MimeMessageHelper(message, true);

	        // Set the email properties
	        helper.setTo(email);
	        helper.setSubject("OTP From E-com Spring");
	        helper.setText(emailContent, true); // true means it's an HTML email

	        // Send the email
	        mailSender.send(message);
	        
	    } catch (MessagingException e) {
	        System.out.println("Error in sending OTP email: " + e.getMessage());
	    }

	    return otp;
	}
	
	private  String genereateOtp() {
//		String source = "0123456789";
//		StringBuffer otp = new StringBuffer();
//		for(int i=0;i<6;i++) {
//			otp.append(source.charAt((int) (Math.random()*source.length())));
//		}
//		return otp.toString();
		SecureRandom random = new SecureRandom();
		int otp = 100000 + random.nextInt(900000);
		return String.valueOf(otp);
	}
}
